### ISSUE TITLE
.

### ISSUE THREAD

**Issue by sebastianjnuwu** [zDubsCrazy/dbs-auto-shop-plugin#1]

**Comment by warleysr** [comment]
Existe, só baixar, mas não sei se ainda é funcional, só testando para saber.

**Comment by sebastianjnuwu** [comment]
Pq fiz uma loja e eu estou tentando fazer o plugin pelo seu pq ele é mais fácil mais encontrei uns erros para fazer o meu! Ahh ótimo repositório da loja difícil encontrar bons assim!

**Comment by warleysr** [comment]
Certo, tem só **6 anos** que fiz isso mas se quiser entrar em contato posso tentar te ajudar com alguma coisa: Warley#6109

**Comment by sebastianjnuwu** [comment]
Tá bom entrarei ao contato!

**Comment by sebastianjnuwu** [comment]
Tem só 6 anos kkkkk mais server muito ainda de aprendizagem kkkk
